[package]
name = "quick-start"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true
strip = "none"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "*"
